# file: playbook-install-firefox.yml
---
- name: chocolatey with ansible
  hosts: windows
  tasks:
    - name: Install common softwares on Windows Machine
      win_chocolatey: name={{ item }} state=latest
      with_items:
        - firefox
        - googlechrome
        - notepadplusplus.install
        - git
        - putty.install
        - 360ts
        - git.install
        - 7zip.commandline
        - 7zip.install
      ignore_errors: yes
