---
- name: launching an ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false 

  vars_files:
   - keypair.yml 

  tasks: 
  - name: search for the latest rhel 7 ami
    ec2_ami_find:
      region: us-east-1
      owner: "309956199498"
      name: "RHEL-7.2*"
    register: find_results

  - debug: var=find_results

  - name: find a subnet id
    ec2_vpc_subnet_facts:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: us-east-1
    register: subnet_ids

  - debug: var=subnet_ids

  - name: launch an ec2 instance
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      instance_type: t2.micro
      region: us-east-1
      image: "{{find_results.results[0].ami_id}}"
      instance_tags:
         Name: mperz
      wait: yes
      vpc_subnet_id: "{{subnet_ids.subnets[0].id}}"
      assign_public_ip: yes